<?php if (!Mage::helper('core/cookie')->isUserNotAllowSaveCookie()): ?>

<?php $accountId = Mage::getStoreConfig(Mage_GoogleAnalytics_Helper_Data::XML_PATH_ACCOUNT) ?>

<!-- BEGIN GOOGLE ANALYTICS CODEs -->
<script type="text/javascript">
//<![CDATA[
    var _gaq = _gaq || [];
    <?php echo $this->_getPageTrackingCode($accountId) ?>
    <?php $code = $this->_getOrdersTrackingCode() // now we store it ?>
	<?php echo $code; ?>

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

//]]>
</script>
<!-- END GOOGLE ANALYTICS CODE -->

<?php if(Mage::getStoreConfig('abtesting/accounts/active')): ?>

<?php $accountId = Mage::helper('abtesting')->getCode() ?>
<?php if($accountId && $accountId != ""): ?>
<!-- BEGIN GOOGLE ANALYTICS CODEs -->
<script type="text/javascript">
//<![CDATA[
    var _gaq = _gaq || [];
    <?php echo $this->_getPageTrackingCode($accountId) ?>
	<?php echo $code; ?>

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

//]]>
</script>
<!-- END GOOGLE ANALYTICS CODE -->
<?php endif; ?>

<?php endif; ?>

<?php endif; ?>
